nette/tracy

src/Tracy/assets/Bar/info.panel.phtml
Helps to identify if xdebug is trully loaded, which also affects the speed of application.
=> Panel: add xdebug version to info panel

src/Tracy/assets/Bar/bar.js
the script tag can be used for other things than javascript - script tags with a different "type" than text/javascript shouldn't be assumed to be javascript
=> evalScript: only evaluate *javascript* scripts

src/Tracy/assets/Bar/bar.js
Current behavior breaks for example [Nextras Mail Panel](https://github.com/nextras/mail-panel/blob/e238dd9d0311f941f3f09433094059b15c49d4f4/src/MailPanel.latte#L1-L40).
=> Tracy does not preserve panel id when moving panel to new window

src/Tracy/assets/BlueScreen/bluescreen.css, src/Tracy/assets/BlueScreen/bluescreen.phtml, tests/Tracy/Debugger.E_ERROR.html.expect, tests/Tracy/Debugger.E_ERROR.html.php5.expect, tests/Tracy/Debugger.E_ERROR.html.xdebug.expect, tests/Tracy/Debugger.error-in-eval.expect, tests/Tracy/Debugger.exception.html.expect, tests/Tracy/Debugger.strict.html.expect
Just an idea. New lines are rarely present in exception messages, but when they do, they usually have a good reason.
=> BlueScreen: preserve whitespace in message

src/Tracy/assets/Bar/bar.js
I copy pasted the code to avoid refactoring.
---
The broken tests are not caused by this PR.
=> bar.js: fixed evaluating script tags in panels in window-mode

src/Tracy/Debugger.php, src/Tracy/assets/Bar/bar.js, src/Tracy/assets/Bar/panels.phtml, tests/Tracy/Debugger.barDump().expect, tests/Tracy/Debugger.barDump().phpt, tests/Tracy/Debugger.barDump().showLocation.phpt, tests/Tracy/Debugger.warnings.html.phpt
Similarly to how we delay rendering of invisible dumps we should delay rendering of invisible panels and render them the first time they became visible. This is especially important when bar panel contains a lot of HTML (for example query log).
What do you think?
=> Delay panel rendering

src/Tracy/assets/Bar/bar.css, src/Tracy/assets/Bar/bar.js
When `toWindow()` failed in `restorePosition`, the panel ended up in an invalid state. This PR resolves this problem in two ways – by making `.tracy-panel` hidden be default and by falling back to `toFloat` when toWindows fails.
=> bar.js: restorePosition does not handle toWindow error

src/Tracy/assets/Bar/bar.css
Since fe7df9ab3361329225686108339838b4304d50f6 the content of a Tracy panel has been hidden when you put it in a new window.
This css change returns the origin behaviour.
=> Fix for a hidden panel content in a new window.

src/Bridges/Nette/TracyExtension.php
See #198
I've disabled Session/Debugger dispatching in for CLI SAPI.
It's needed [only for Ajax](https://github.com/nette/tracy/pull/198#issuecomment-227082488).
=> TracyExtension: Don't dispatch Debugger in a CLI

src/Tracy/Bar.php
Explicitly set the CSS to UTF-8 so the toggle triangles display properly on HTML pages that do not declare UTF-8 encoding.
=> Sets CSS to UTF-8 for toggle triangle chars

src/Tracy/Dumper.php
`iconv_substr` is very f*cking slow. Even the do-while fallback is few thousand times faster :D
=> Dumper::encodeString - use mb_substr

readme.md
Because it sends a separate HTTP request now (see 13f854d4c11221add4697121e183a147732bb13b) it needs to load  JS from the domain itself, too.
Thanks!
=> Tracy requires 'self' in CSP since 2.4

src/Tracy/assets/BlueScreen/content.phtml
Purpose of this pull request is to give user-defined panels in bluescreen possibility to declare whether they want to be collapsed or expanded.
Now, if you implement Bluescreen panel, you must return from your callback array with two keys - `panel` and `tab`. After this PR we will support third optional key - `collapsed`.
=> Ability to set whether bluescreen panel is collapsed or not

src/Tracy/assets/Bar/bar.phtml
Tracy is now showing in Safari. See:
https://forum.nette.org/cs/26892-nefunkcni-tracy-v-prohlizeci-safari
https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded
=> Tracy is now showing in Safari.

src/Tracy/assets/Bar/bar.css, src/Tracy/assets/BlueScreen/bluescreen.css
- bug fix? yes
I just made Tracy more sexy :) There is [issue opened](https://github.com/nette/tracy/issues/206) that shows headings being affected by CSS property with `!important` set on. I have fixed this particular case (for headings and paragraphs).
Another problem occured on page with styled pseudoelements `:before` or `:after`. On my page, there are styled headings that are decorated by these pseudoelements. Sadly, Tracy rendered these as well and so its layout went broken. Now, after my fixes, any pseudoelements inside Tracy will be hidden by default except cases where it is need for it.
=> bar.css, bluescreen.css: fixed leaks of page's default CSS into Tracy

src/Tracy/assets/Bar/bar.js
- bug fix? no
- new feature? yes
- BC break? no
- doc PR: doesn't seem necessary
This pull request adds AJAX debug bar support for requests made via [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead of `XMLHttpRequest`.
There is one caveat which, however, should imo be addressed in the userland: `fetch()` must be sent with `credentials` set to `include` or `same-origin` for the cookies to be passed and thus for the debug bar session storage to work. This implementation sanely defaults to `same-origin` if the option is not provided, but if the user sends their own `Request` object, the `credentials` option defaults to `omit` if not provided, and cannot be overridden. I believe it should be left up to the user to handle such situations.
=> Display AJAX bar for Fetch requests

src/Tracy/assets/Debugger/error.500.phtml
- bug fix? no  
- new feature? yes
- BC break? no
- doc PR: not applicable
Often i get emailed screenshots of the 500 error page, if it showed the date/time on the page, it would be much easier to find the relevant logs.
This change does not require any additional tests.
=> Show date/time error occurred

src/Tracy/Debugger.php
The context argument of an error handler is optional. Furthermore, it will be deprecated in PHP 7.2 (see http://www.php.net/manual/en/function.set-error-handler.php).
- bug fix? yes
- new feature? no
- BC break? no
- doc PR: -
=> make the error handler context argument optional

src/Tracy/assets/Bar/info.panel.phtml
- bug fix? yes
- BC break? no
Field `source` is not mandatory. For example, my local repositories
mirrored from a path do not have the field in `composer.lock`. Refs
to `source` and `dist` are the same on all my dependencies and even
in file `Locker.php` of `composer/composer` package there is the
retrieval of reference ID fall-backed by using `dist` field.
https://github.com/composer/composer/blob/28e41d094e78e0a60dc5123ee572701154008848/src/Composer/Package/Locker.php#L417
=> info.panel.html: fix undefined property in list of composer packages

src/Tracy/assets/Bar/bar.js
- bug fix? yes
- new feature? no
- BC break? no
Not sure if this is the most elegant solution, but currently in 2.5-dev if you click the 'close debug bar' icon and reload the page, the bar ends up at the top left of the viewport. This is because when `display: none`, the `isAtTop()` method always returns true. My fix prevents updating the saved position (via `savePosition()`) when the bar is hidden (`display:none`).
=> Fix shifting of bar to top right when reloading page after closing/hiding

src/Bridges/Nette/TracyExtension.php
fixed accessing $this->builder property which doesn`t exist, replaced with use of correct local variable $builder
- bug fix #300
- BC break? yes
=> Fixed undeclared propery error

tools/open-in-editor/windows/open-editor.js
- bug fix: yes
- BC break: no
Search and replace parameter can be empty when user click to path for open the file.
=> Open-editor windows script - fix url match regex

tools/open-in-editor/linux/open-editor.sh
- New feature.
- No BC break intended.
- Based on: https://twitter.com/geekovo/status/997538920278773761
Updated Linux "open-editor" bash script to support the new *"create"* and *"fix"* actions that can now be used via the `editor://` protocol.
- Traditional **`open` action**:
- Should behave the same as always.
- New **`create` action**:
- Will create file at the location specified in the `file` parameter, **if it does not already exist**. Then opens the file.
- Any necessary but non-existing directories are created (recursively).
- New **`fix` action**:
- Performs search (`search` param) and replace (`replace` param) in the file (`file` param) at the specified line (`line` param, if specified). Then opens the file.
- Fails if the file does not exist.
- The order of GET parameters in …
=> Linux "open-editor" supports "create" and "fix" actions.

tools/open-in-editor/windows/open-editor.js
- bug fix
- BC break? no
To be compatible with older Tracy.
=> open-editor.js: backward compatible regexp

composer.json, src/Bridges/Psr/PsrToTracyLoggerAdapter.php, src/Bridges/Psr/TracyToPsrLoggerAdapter.php, tests/Tracy.Bridges/PsrToTracyLoggerAdapter.phpt, tests/Tracy.Bridges/TracyToPsrLoggerAdapter.phpt
@dg Would you accept PR with PSR-3 adapter? So it would be possible to use any PSR-3 compatible logger (e.g. Monolog) with Tracy, i.e. the following would be possible
~~~php
$psrLogger = new Monolog\Logger(...);
$tracyLogger = new Tracy\Bridges\Psr\PsrLoggerAdapter($psrLogger);
Tracy\Debugger::setLogger($tracyLogger);
~~~
Or we could even apply the adapter automatically, so the following would be possible:
~~~php
$psrLogger = new Monolog\Logger(...);
Tracy\Debugger::setLogger($psrLogger);
~~~
=> PSR-3 adapter

src/Tracy/assets/Bar/loader.phtml
... so that `<base href>` won't prevent Tracy from loading
=> Added DOCUMENT_URI to script src

src/Tracy/Bar.php
- Type: bug fix
- BC break: yes, but probably no effective
- No tests or docs affected or applied
Tracy is sending Tracy\Bar components with `Content-Type: text/javascript`.
According to [RFC 4329](https://www.rfc-editor.org/rfc/rfc4329.txt) (chapter 7.1) is `text/javascript` **obsolete** and should be used `application/javascript` instead.
In real case it make light impediment to right detect, and process response. For example [`.htaccess` in nette/web-project](https://github.com/nette/web-project/blob/7132061169a4f1f66c443a58e06ccc26b6964807/www/.htaccess#L26) is set `DEFLATE` filter only for `application/javascript` mime. I mean it's just mistake, not intentionally.
=> bar.js: send with Content-type: application/javascript

src/Tracy/BlueScreen.php
- bug fix / new feature? minor low-level feature
- BC break? no
- doc PR: too low-level to be worth documenting
I need to upload the bluescreen to remote storage (AWS S3 in my case). This is what I'm doing currently
```php
$lockPath = "$localPath.lock";
$lockHandle = @fopen($lockPath, 'x');
if ($lockHandle === false) {
return;
}
Tracy\Debugger::getBlueScreen()->renderToFile($exception, $localPath);
$this->remoteStorageDriver->upload($localPath);
@fclose($lockHandle);
@unlink($lockPath);
```
The proposed change would allow to simplify to code to
```php
if (Tracy\Debugger::getBlueScreen()->renderToFile($exception, $localPath)) {
$this->remoteStorageDriver->upload($localPath);
}
```
=> BlueScreen: renderToFile() returns bool to indicate if file was written by current process

src/Tracy/assets/Bar/bar.js
- new feature
- BC break? no
Calls `Bar.autoHideLabels()` method on every resize of viewport. This is useful when testing web responsivness - you resize the viewport all the time but Tracy does not react with showing/hiding labels when there is (not) enough of space.
Even better would be media query driven showing/hiding.
=> Recount hiding of labels when resized

src/Tracy/BlueScreen/assets/content.phtml
- bug fix
- BC break? no
- doc PR: -
Cherry pick of commit 2fbe913f09ad6735d3182af760b75111f2b1b5dd from `master` to `v2.6` branch.
That fixes syntax error of Blueprint template on `short_open_tag=Off` PHP configuration.
=> Fix "syntax error, unexpected end of file" error

src/Tracy/BlueScreen/BlueScreen.php
- bug fix
- BC break? yes
Original regex does not support json syntax with escaping in message highliter.
Example:
New pattern support quotation escaping:
=> Add support for escaping (for example in json).

src/Bridges/Psr/PsrToTracyLoggerAdapter.php, tests/Tracy.Bridges/PsrToTracyLoggerAdapter.phpt
- new feature
- BC break? no
Some loggers (e.g https://github.com/bzikarsky/gelf-php) may require a non-empty log message. Adding the exception class, code and file to the log message solves this problem.
=> PsrToTracyLoggerAdapter: changed the log message

src/Tracy/Debugger/Debugger.php
The value of 30000 bytes was an incorrect representation of the previous "scientific notation value" of "3e5". I can only assume the notation was changed to increase readability, but the change was done improperly and introduced a regression.
Also the number of bytes reserved for the error renderer was increased to 500 kB, since 300 kBs wasn't enough for the whole error page to render correctly.
- bug fix for issue: *Catching memory exhaustion #272*
- BC break? *Shouldn't be...*
=> Increase size of memory reserve for Debugger

tools/open-in-editor/linux/open-editor.sh
File path mapping shut be done before using of path.  
For actions `fix` and `create` was mapping done after realization of action.
workaround: set mapping in tracy config.
- bug fix 
- BC break? no
- doc PR: not necessary
=> Path mapping before using of path.

src/Tracy/Bar/panels/info.panel.phtml
- new feature
- BC break? no
Sometimes beginners have a problem understanding that `127.0.0.1` or `::1` is localhost.
I think Tracy should explain it in brackets:
Thanks.
=> InfoPanel: Add information about localhost IP.

src/Bridges/Nette/Bridge.php
- bug fix
- BC break? no
In case of Latte error in template render multiple of border. Now fixed.
Old render style:
New style:
Thanks.
=> Bridge: Remove redundant <pre> and <div>.

src/Bridges/Nette/Bridge.php
- bug fix
- BC break? no
In case of template error line is null Tracy can not render filename:
Fixed to:
=> Bridge: Template line can be null.

src/Bridges/Nette/TracyExtension.php
Removes `Tracy\Debugger::$editorMapping = [];` from generated container
=> editorMapping is null by default

src/Tracy/BlueScreen/assets/content.phtml
- new feature
- BC break? no
Added icon for open link to new window:
=> Content: Add link as new window

src/Tracy/Bar/panels/info.panel.phtml
- new feature
- BC break? yes
Very often I need to find out what production server the site is running on. This feature should be very useful.
=> Info panel: Add server name by IP

src/Tracy/Logger/Logger.php
PHP 7+ no more thrown warning when timezone not set.
- new feature
- BC break? no
- doc PR: not needed
- Nette Tracy is required PHP 7 +
- PHP 7 is no mote throw warning on using `date`-like functions without defined current TimeZone
- Silent error marker on `@date()` function is no more needed.
- https://hakre.wordpress.com/2016/01/03/history-of-the-php-date-timezone-settings-warning/
- https://github.com/php/php-src/pull/1029
Thanks for this great tool ❤️
=> Logger: Remove shut-up marker on date()

src/Tracy/Bar/panels/info.panel.phtml
- bug fix
- BC break? no
I think this is more better way how to detect real server IP and real server name. Supports simple server architecture and Ngnix as reverse proxy.
Explanation: https://php.baraja.cz/ip-adresa (czech language).
Thanks.
=> Info panel: Better detection server IP and server name.

src/Tracy/Bar/assets/bar.js
In project I am currently working on, I also wrap `fetch()` method and return the result as `json` object, but tracy doesn't check if the response is actually a Response object.
So it thinks my json object is `Response` object and tries to access `.headers` property, that may not exist and then run function `has()` on it.
- bug fix
- BC break? no
=> bar.js: fetch checks Response

src/Tracy/BlueScreen/BlueScreen.php, src/Tracy/Dumper/Describer.php, src/Tracy/Dumper/Dumper.php, tests/Tracy/BlueScreen.getDumper().phpt, tests/Tracy/Dumper.dump().cli.phpt, tests/Tracy/Dumper.scrubber.phpt
This feature adds possibility to define/configure a custom "scrubber" in a flexible way.
A scrubber allows for custom variable filtering to prevent sensitive data leak.
It expands the currently built-in "keys to hide" scrubbing mechanism, and should IMHO replace it by next major release.
This allows for (among others):
- scrubbing based on value and/or keys (current scrubbing only works with keys)
- scrubbing based on regexp matching (current scubbing only matches exact match, case-insensitive)
```php
Tracy\Debugger::getBlueScreen()->scrubber = function(string $key, $val = null): bool {
return
preg_match('#password#i', $key) ||
( is_string($val) && preg_match('#^https://#i', $val) )
;
}
```
... and any logic users want to _easily_ fit into it.
> Backwards compatibile.
Closes #431
=> Scrubber mechanism

src/Tracy/BlueScreen/BlueScreen.php, tests/Tracy/BlueScreen.showEnvironment.phpt
This is a new feature that allows us to omit the Environent section from the output.
```php
// hide the environment section (shown by default)
Tracy\Debugger::getBlueScreen()->showEnvironment = false;
```
This refers to #430 issue.
=> Allow to hide the Environment section by configuration

src/Tracy/Bar/panels/info.panel.phtml
- new feature
- BC break? no
PHP 8 is supports JIT. Would be nice to show if its enabled.
=> Info panel JIT

src/Tracy/Bar/panels/errors.panel.phtml
- bug fix
- BC break: no
- Target version: `v2.7` because it's bug
Currently is unable to open `editor:` link in Tracy error panel, because the TracySort handler is catching that click.
This PR is adding table header for Error panel to prevent conflict links in content with sorting feature.
Project contains more sortable tables, only error panel contains anchors and sorting feature together.
=> [bugfix] Bar: fix clickable link in sortable tables

src/Tracy/Debugger/Debugger.php
- bug fix   
- BC break? no
The value `7` is mentioned in release notes of [2.8.0](https://github.com/nette/tracy/releases/tag/v2.8.0) and in [README](https://github.com/nette/tracy#variable-dumping)
=> Debugger::$maxDepth changed to 7

readme.md, src/Tracy/BlueScreen/assets/bluescreen.css
- new feature
- BC break? no
Hello,
on some systems (like Ubuntu) the user may have a red color to selection the text.
This fix sets the default color for the selection to always the same yellow (according to the code background) and the text as black.
Original example:
New example:
Thanks.
=> Bluescreen: Add selection color

src/Tracy/Debugger/Debugger.php
- bug fix 
- BC break: no
When opening browser from CLI, editor mappings are not applied.
=> Update Debugger: apply editor mapping for browser from CLI

.github/workflows/tests.yml, src/Tracy/Dumper/Dumper.php, src/Tracy/Dumper/Exposer.php, tests/Tracy/Dumper.toText().specials.ds.phpt
=> Dumper: added ext-ds support

src/Tracy/Debugger/Debugger.php
I just don't think there is a reason to not show error message in console. But I may be wrong, let me know if I missed something.
=> Debugger: shows error message in console

src/Tracy/BlueScreen/BlueScreen.php, src/Tracy/Debugger/Debugger.php
- new feature
- BC break? no
Rel #490
A simple tool for plotting an uncaught exception (or other error) directly to the terminal in CLI mode. It makes it very easy to debug the application on the server.
Real example:
Thanks!
=> Debugger: render code snipet in CLI on error (#494)(#490)

src/Tracy/BlueScreen/assets/content.phtml
Two sections of BlueScreen were previously not properly scrubbed:
- HTTP Reqeust / Headers
- CLI Request / Arguments
This includes, for example, the `Cookie` header, which can easily be used to hijack the session:
The Cookie is plaintext-legible in the `Headers` section, while the `$_COOKIE` section right below gets properly scrubbed:
This PR fixes the issue.
- bug fix
- BC break? no
=> BlueScreen: used scrubber for HTTP headers

src/Tracy/BlueScreen/assets/content.phtml
- bug fix / new feature?   bug fix of #504
- BC break? no
This pull requests solve the #504 issue, where debugging window does not know the variable $exceptions in AJAX requests.
=> Undefined variable $exceptions in AJAX requests fix

composer.json, src/Bridges/Psr/TracyToPsrLoggerAdapter.php, tests/Tracy.Bridges/PsrToTracyLoggerAdapter.phpt
- new feature
- BC break? yes
- doc PR: not needed?
Minimum needed to be compatible with psr/log ^3.0. It should be safe to do on PHP >=7.2, any extending class just have to add return type too.
=> Compatibility with psr/log ^2.0 and ^3.0

src/Bridges/Nette/TracyExtension.php, src/Tracy/Debugger/Debugger.php, tests/Tracy.Bridges/TracyExtension.services.phpt, tests/Tracy/Debugger.scream.E_USER_DEPRECATED.phpt, tests/Tracy/expected/Debugger.scream.E_USER_DEPRECATED.expect
- new feature
- BC break? no
- doc PR: TBA if accepted
`Debugger::$scream` is currently simple on/off switch that unmutes all/none of the suppressed errors. This PR adds support for selecting which error severities should be unmuted.
This feature might be useful e.g. for tracking and logging of deprecation errors triggered in "muted" state by some of the popular libraries, see:
- https://github.com/doctrine/deprecations/blob/master/lib/Doctrine/Deprecations/Deprecation.php#L189
- https://github.com/symfony/deprecation-contracts/blob/main/function.php#L25
Setting `Debugger::$scream = E_USER_DEPRECATED` would cause all the deprecations to be tracked by Tracy, while still ignoring all other muted error types.
Second commit adds/improves the support for error severity configuration in …
=> Allow to select error severity for Debugger::$scream

src/Tracy/Debugger/Debugger.php
hrtime is faster on virtual machines, due microtime use system call that need to change context from user to kernel (PHP7.3+)
- bug fix / new feature?   optimalization
- BC break? no
- doc PR: nette/docs#???  not needed
=> Debugger::timer: switch from microtime to hrtime

src/Tracy/Session/FileSession.php
- bug fix
- BC break? no
There is a problem with locking when you use php to execute  bash script with background processes eg. https://stackoverflow.com/questions/71929617/php-8-1-not-release-flock-after-calling-exec
Unlocking before fclose seems to be a solution.
=> Unlock session file before close

src/Tracy/assets/table-sort.js
We noticed when using the table sort that it would sort things alphabetically instead of numerically (if the field happened to start with a number). This fixes it while maintaining alphabetical sorting.
- Improvement: Table sorting
- BC break? no
- doc PR: It's an internal fix that doesn't need to be documented
The problem we were running into is that we would have errors in our project sort like the following:
- 1x
- 1x
- 145x
- 2x
- 201x
- 3x
- 4x
- etc.
It is the same for measuring database query times, etc. Anything numeric with text in it, it would kinda choke. Adding these couple extra arguments to the localeCompare() function allows it to sort numerics properly while maintaining alphabetical sorting.
BTW, looked for unit tests for your js stuff, but didn't find anything :grimacing:
=> Sort with natural sort instead.

composer.json, src/Bridges/Nette/MailSender.php, src/Bridges/Nette/TracyExtension.php
- new feature? yes
- BC break? I don't think so
When  using nette behind proxy or in containers, server name is localhost. When nette/http is used, it reads actual host from proxy headers - https://github.com/nette/http/blob/7a92a2a61aaf2ebb74df11bb4a6f56daf20a1ef6/src/Http/RequestFactory.php#L294
=> Server name from nette/http

src/Tracy/Debugger/Debugger.php
I assume this is a bug and the option should be passed along with the others to allow setting max array items.
=> Pass Debugger::maxItems option to Dumper in Debugger:barDump()

src/Tracy/BlueScreen/assets/section-cli.phtml
- bug fix
- BC break? no
Variable argv does not have to be present. First check relates to Helper class, which does not add column into source when run from cli and argv is missing
https://github.com/nette/tracy/blob/209ac3040406e31ac4ab20a06cfcd0513a719b36/src/Tracy/Helpers.php#L173
=> Added checks if $_SERVER['argv'] is set

src/Tracy/Helpers.php, tests/Tracy.Bridges/TracyExtension.services.phpt
- bug fix
- BC break? no
`E_STRICT` error level has not been used since PHP 8.0. PHP 8.4 started emitting deprecation warning on any usage of `E_STRICT` constant.
Tracy 2.10 requires min PHP 8.0, so this can be completely dropped.
See https://php.watch/versions/8.4/E_STRICT-deprecated
=> Drop obsolete E_STRICT error level
