nette/tracy

- composer.json
- src/Bridges/DI/TracyExtension.php
- tests/Tracy.Bridges/TracyExtension.services.phpt
see nette/bootstrap#4
Closes #58
> Added bridge for Nette Framework

- src/Bridges/Nette/TracyExtension.php
Not tested, but hopefully it will work =)
> TracyExtension: added options logDirectory and logSeverity

- src/Tracy/assets/Bar/bar.css
- src/Tracy/assets/Bar/bar.js
*While working on certain tracy panel…*
I discovered annoying inconsistency in how panels are rendered in window mode.
> bar.css: padding of panel in window-mode is consistent with other modes

- src/Tracy/assets/Bar/bar.css
- src/Tracy/assets/Bar/bar.js
All browsers except for Chrome have trouble rendering them.
> Fix opacity hover effect on panels

- src/Tracy/assets/Bar/bar.js
I don't know why. I'll look into it.
> AJAX Tracy does work over HTTPS

- src/Tracy/assets/Bar/bar.js
https://github.com/nette/tracy/issues/182 led me to discovery of another minor bug
> bar.js: excluded scrollbars from available viewport dimensions

- src/Bridges/Nette/TracyExtension.php
- tests/Tracy.Bridges/TracyExtension.services.phpt
https://forum.nette.org/cs/26317-jak-nastavit-vlastni-logger#p174402
> tracy.logger definition can be changed in config

- src/Tracy/assets/Bar/bar.js
please refer to this issue #209
> fix protol-less ajax url request not recorded

- src/Tracy/Bar.php
Fixed: https://forum.nette.org/cs/26772-problem-s-cookie-path-podle-url
> Fixed assets path if session path is different

- src/Tracy/Logger.php
https://github.com/nette/tracy/blob/master/src/Tracy/Logger.php#L94 (works only because of BC)
> Fix implode args order

- src/Bridges/Nette/TracyExtension.php
- bug fix? yes #274
- new feature? yes
- BC break? no
- doc PR: no
> TracyExtension: add configuration directive maxLength [closes #274]

- src/Tracy/assets/Bar/bar.css
This seems to fix https://github.com/nette/tracy/issues/290 although it isn't well tested and it mostly just undoes some of your recent changes. Also not sure about the calc - 100px but otherwise the horizontal scrollbar appears for the page.
> Attempted fix for panels not appearing above other elements with defined z-index

- examples/ajax.php
- src/Tracy/Bar/Bar.php
- src/Tracy/Bar/assets/bar.css
- src/Tracy/Bar/assets/bar.js
- src/Tracy/Helpers.php
(I don't know how to collaborate on existing PR, so I created another one. I found only info how to enable it https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork. If you know how to do it, please write me.)
This is #336 rebased on Tracy 2.6.
The only problem I see is how to set the limit of displayed AJAX requests. The deleting button is imho unnecessary, the limit is better.
> Show all XHR requests in bar (#199,#336)

- readme.md
- documentation improvement
- BC break? no
> A logDirectory should be provided to write to file

- readme.md
Which I found out after noticing that "somehow" the error reporting level of my application changed. Traced it down to Tracy 😄
> readme: info about error_reporting(E_ALL) is used

- readme.md
> Readme: switched "port" for "integration"

- src/Tracy/Debugger/ProductionStrategy.php
- bug fix
- BC break? no
This is described here https://github.com/php/doc-en/issues/1581
> fwrite on closed resource fix

- src/Tracy/Dumper/Exposer.php
- tests/Tracy/Dumper.toText().specials.ds.phpt
Fixes https://github.com/nette/tracy/issues/560
> clone Ds\Collection

- .github/workflows/coding-style.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
- composer.json
- eslint.config.mjs
- package.json
- readme.md
- src/Tracy/Bar/assets/bar.js
- src/Tracy/BlueScreen/assets/bluescreen.js
- src/Tracy/Dumper/assets/dumper.js
- src/Tracy/Logger/Logger.php
- src/Tracy/assets/table-sort.js
- src/Tracy/assets/tabs.js
- src/Tracy/assets/toggle.js
Init Tabs for Debug bar panels.
> Update bar.js - init Tabs

- src/Tracy/BlueScreen/BlueScreen.php
- tests/Tracy/Debugger.exception.in-generator.html.phpt
- tests/Tracy/expected/Debugger.exception.in-generator.html.expect
- bug fix: #595 
- BC break? no
> BlueScreen: fixed PHP 8.4 exception in generator
